"use client";

import React, { useState } from "react";
import Link from "next/link";
import { 
  Scale, 
  AlertTriangle, 
  ShieldAlert, 
  FileCheck2, 
  PhoneCall, 
  ExternalLink, 
  BookOpen, 
  FileText,
  ChevronDown,
  ChevronUp,
  Search
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Sidebar } from "@/components/layout/sidebar";
import { Header } from "@/components/layout/header";
import { ProtectedRoute } from "@/components/auth/protected-route";

interface LegalSection {
  section: string;
  title: string;
  act: string;
  description: string;
  penalties: string;
  relevance: string;
}

const STATUTORY_SECTIONS: LegalSection[] = [
  {
    section: "Section 66D",
    title: "Cheating by Personation Using Computer Resource",
    act: "Information Technology Act, 2000",
    description: "Applies directly to phishing schemes, fraudulent banking portals, spoofed sender domains, and fake job/lottery scams where an offender impersonates a legitimate entity to deceive victims.",
    penalties: "Imprisonment up to 3 years and fine up to ₹1,00,000.",
    relevance: "Primary statutory provision for reporting malicious URLs and phishing scams detected by CyberGuard AI."
  },
  {
    section: "Section 66C",
    title: "Identity Theft & Credential Theft",
    act: "Information Technology Act, 2000",
    description: "Fraudulently or dishonestly making use of the electronic signature, password, or any other unique identification feature of any other person.",
    penalties: "Imprisonment up to 3 years and fine up to ₹1,00,000.",
    relevance: "Applicable when malicious websites harvest user login credentials, OTPs, or session tokens."
  },
  {
    section: "Section 43 & 43A",
    title: "Damage to Computer Systems & Failure to Protect Data",
    act: "Information Technology Act, 2000",
    description: "Penalty and compensation for unauthorized access, downloading data, introducing viruses, denial of service, and failure of corporate bodies to protect sensitive personal data.",
    penalties: "Civil liability; compensation to the victim for damages caused.",
    relevance: "Governs corporate data breach responsibilities and unauthorized malware deployments."
  },
  {
    section: "Section 66",
    title: "Computer-Related Offenses & Hacking",
    act: "Information Technology Act, 2000",
    description: "Dishonestly or fraudulently committing any act referred to in Section 43 that alters, damages, destroys or diminishes value or utility of computer information.",
    penalties: "Imprisonment up to 3 years or fine up to ₹5,00,000, or both.",
    relevance: "Covers unauthorized server intrusion, defacement, and deliberate exploitation of computer resources."
  },
  {
    section: "Section 65B",
    title: "Admissibility of Electronic Records",
    act: "Indian Evidence Act, 1872 / Bharatiya Sakshya Adhiniyam, 2023",
    description: "Requires a certificate validating that electronic records (screenshots, server logs, forensic hashes) were generated by a computer during regular operational usage without unauthorized alteration.",
    penalties: "Inadmissibility of digital evidence in court if procedural requirements are violated.",
    relevance: "Crucial for producing CyberGuard AI forensic reports and SHA-256 evidence hashes in official court proceedings."
  },
  {
    section: "DPDP Act 2023",
    title: "Digital Personal Data Protection Act",
    act: "Statute of the Republic of India (Act No. 22 of 2023)",
    description: "Establishes a statutory framework for processing digital personal data, safeguarding individuals' privacy rights, and mandating prompt breach reporting to the Data Protection Board.",
    penalties: "Penalties up to ₹250 Crores for significant data breaches and failure to observe security safeguards.",
    relevance: "Mandates security measures against credential stuffing and phishing data leaks."
  }
];

export default function CyberLawPage() {
  const [searchQuery, setSearchQuery] = useState("");
  const [expandedSection, setExpandedSection] = useState<string | null>("Section 66D");

  const filteredSections = STATUTORY_SECTIONS.filter(item => {
    if (!searchQuery.trim()) return true;
    const q = searchQuery.toLowerCase();
    return (
      item.section.toLowerCase().includes(q) ||
      item.title.toLowerCase().includes(q) ||
      item.description.toLowerCase().includes(q) ||
      item.relevance.toLowerCase().includes(q)
    );
  });

  return (
    <ProtectedRoute>
      <div className="min-h-screen flex flex-col lg:flex-row bg-background">
        <Sidebar />
        <div className="flex-1 flex flex-col min-w-0">
          <Header />
          <main className="flex-1 p-4 sm:p-6 lg:p-8 max-w-7xl mx-auto w-full space-y-6">
            
            {/* Header */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <span className="px-2 py-0.5 bg-primary-blue/10 text-primary-blue font-mono font-bold text-[10px] rounded border border-primary-blue/20">
                    STATUTORY DIRECTORY
                  </span>
                  <span className="text-[11px] font-mono text-text-secondary">
                    Legal Frameworks & Law Enforcement Reporting
                  </span>
                </div>
                <h1 className="text-2xl sm:text-3xl font-mono font-bold text-text-primary tracking-tight">
                  Cyber Law & Incident Reporting
                </h1>
                <p className="text-text-secondary text-xs sm:text-sm mt-0.5 max-w-2xl">
                  Authoritative statutory reference, electronic evidence admissibility protocols, and law enforcement escalation procedures.
                </p>
              </div>

              <div className="flex items-center gap-2">
                <Link href="/reports">
                  <Button className="bg-primary-blue hover:bg-primary-blue/90 text-white text-xs px-4 h-9 font-mono font-bold rounded-lg cursor-pointer">
                    View Incident Reports
                  </Button>
                </Link>
              </div>
            </div>

            {/* Mandatory Legal Disclaimer Banner */}
            <div className="p-4 rounded-lg bg-warning/10 border border-warning/30 flex items-start gap-3">
              <AlertTriangle className="h-5 w-5 text-warning shrink-0 mt-0.5" />
              <div className="space-y-1">
                <h4 className="text-xs font-mono font-bold uppercase tracking-wider text-warning">
                  Statutory Reference Notice & Legal Disclaimer
                </h4>
                <p className="text-xs text-text-primary leading-relaxed">
                  The statutory summaries, legal provisions, and evidence preservation guidelines provided on CyberGuard AI are for informational and cybersecurity triage purposes only. They do not constitute formal legal counsel. In the event of a cyber incident, fraud, or extortion, victims should immediately file an official complaint at{" "}
                  <a href="https://cybercrime.gov.in" target="_blank" rel="noopener noreferrer" className="underline font-semibold text-primary-blue inline-flex items-center gap-0.5">
                    cybercrime.gov.in <ExternalLink className="h-3 w-3" />
                  </a>{" "}
                  or dial the National Cyber Crime Helpline at <strong className="font-mono font-bold text-text-primary">1930</strong>. Always verify statutory provisions with official government gazettes or a qualified cyber advocate.
                </p>
              </div>
            </div>

            {/* Emergency Law Enforcement Channels */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <Card className="border-border bg-card p-4">
                <div className="flex items-center gap-2 mb-2 text-primary-blue">
                  <PhoneCall className="h-4 w-4" />
                  <span className="text-xs font-mono font-bold uppercase">National Cyber Helpline</span>
                </div>
                <div className="text-xl font-mono font-bold text-text-primary">
                  1930 (Toll-Free)
                </div>
                <p className="text-[11px] text-text-secondary mt-1">
                  Immediate financial fraud reporting to freeze stolen funds within the Golden Hour.
                </p>
                <div className="mt-3 pt-2 border-t border-border">
                  <span className="text-[10px] font-mono text-text-secondary">Operated by Indian Cyber Crime Coordination Centre (I4C)</span>
                </div>
              </Card>

              <Card className="border-border bg-card p-4">
                <div className="flex items-center gap-2 mb-2 text-primary-blue">
                  <ShieldAlert className="h-4 w-4" />
                  <span className="text-xs font-mono font-bold uppercase">National Portal</span>
                </div>
                <div className="text-xl font-mono font-bold text-text-primary truncate">
                  cybercrime.gov.in
                </div>
                <p className="text-[11px] text-text-secondary mt-1">
                  Official portal to register cyber crime complaints, FIRs, and financial fraud reports online.
                </p>
                <div className="mt-3 pt-2 border-t border-border">
                  <a
                    href="https://cybercrime.gov.in"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-[11px] font-mono text-primary-blue hover:underline inline-flex items-center gap-1"
                  >
                    Open official portal <ExternalLink className="h-3 w-3" />
                  </a>
                </div>
              </Card>

              <Card className="border-border bg-card p-4">
                <div className="flex items-center gap-2 mb-2 text-primary-blue">
                  <FileCheck2 className="h-4 w-4" />
                  <span className="text-xs font-mono font-bold uppercase">CERT-In Emergency Desk</span>
                </div>
                <div className="text-xl font-mono font-bold text-text-primary">
                  incident@cert-in.org.in
                </div>
                <p className="text-[11px] text-text-secondary mt-1">
                  Mandatory reporting of cyber security incidents under CERT-In directives.
                </p>
                <div className="mt-3 pt-2 border-t border-border">
                  <span className="text-[10px] font-mono text-text-secondary">Direct hotline: 1800-11-4949</span>
                </div>
              </Card>
            </div>

            {/* Statutory Reference Sections */}
            <div className="space-y-4">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                <div>
                  <h3 className="text-sm font-mono font-bold uppercase tracking-wider text-text-primary">
                    Applicable Statutory Provisions ({filteredSections.length})
                  </h3>
                  <p className="text-xs text-text-secondary">
                    Information Technology Act, 2000, Bharatiya Sakshya Adhiniyam, and DPDP Act provisions.
                  </p>
                </div>

                <div className="relative w-full sm:w-64">
                  <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-text-secondary pointer-events-none" />
                  <input
                    type="text"
                    placeholder="Search sections or offenses..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="w-full h-8 pl-8 pr-3 text-xs bg-muted/60 border border-border rounded-md text-text-primary placeholder:text-text-secondary focus:outline-none focus:ring-1 focus:ring-primary-blue"
                  />
                </div>
              </div>

              <div className="space-y-3">
                {filteredSections.map((item) => {
                  const isExpanded = expandedSection === item.section;
                  return (
                    <Card 
                      key={item.section}
                      className="border-border bg-card shadow-xs transition-all overflow-hidden"
                    >
                      <button
                        type="button"
                        onClick={() => setExpandedSection(isExpanded ? null : item.section)}
                        className="w-full text-left p-4 flex items-center justify-between gap-4 cursor-pointer hover:bg-muted/30 transition-colors"
                      >
                        <div className="flex items-center gap-3 min-w-0">
                          <span className="px-2 py-0.5 rounded font-mono font-bold text-xs bg-primary-blue/10 text-primary-blue border border-primary-blue/20 shrink-0">
                            {item.section}
                          </span>
                          <div className="min-w-0">
                            <span className="font-semibold text-xs text-text-primary block truncate">
                              {item.title}
                            </span>
                            <span className="text-[11px] text-text-secondary font-mono">
                              {item.act}
                            </span>
                          </div>
                        </div>

                        <div className="shrink-0 text-text-secondary">
                          {isExpanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
                        </div>
                      </button>

                      {isExpanded && (
                        <div className="px-4 pb-4 pt-1 border-t border-border space-y-3 bg-card-elevated/20 text-xs">
                          <div>
                            <span className="text-[10px] font-mono uppercase text-text-secondary font-semibold block">
                              Statutory Scope & Description
                            </span>
                            <p className="text-text-primary mt-0.5 leading-relaxed">
                              {item.description}
                            </p>
                          </div>

                          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-1">
                            <div className="p-2.5 rounded bg-muted/50 border border-border">
                              <span className="text-[10px] font-mono uppercase text-warning font-semibold block">
                                Penalties / Liabilities
                              </span>
                              <p className="text-text-primary font-mono text-[11px] mt-0.5">
                                {item.penalties}
                              </p>
                            </div>

                            <div className="p-2.5 rounded bg-muted/50 border border-border">
                              <span className="text-[10px] font-mono uppercase text-primary-blue font-semibold block">
                                CyberGuard AI Platform Relevance
                              </span>
                              <p className="text-text-primary text-[11px] mt-0.5">
                                {item.relevance}
                              </p>
                            </div>
                          </div>
                        </div>
                      )}
                    </Card>
                  );
                })}
              </div>
            </div>

            {/* Evidence Preservation Checklist */}
            <Card className="border-border bg-card p-5 space-y-4">
              <div className="flex items-center gap-2">
                <BookOpen className="h-4 w-4 text-primary-blue" />
                <h3 className="text-xs font-mono font-bold uppercase tracking-wider text-text-primary">
                  Forensic Chain of Custody & Evidence Preservation Protocol
                </h3>
              </div>
              <p className="text-xs text-text-secondary">
                To ensure digital evidence collected from CyberGuard AI is legally admissible under Section 65B:
              </p>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
                <div className="p-3 rounded-lg border border-border bg-card-elevated/40 space-y-1">
                  <span className="font-semibold text-text-primary block font-mono">1. Preserve Original Artifacts</span>
                  <p className="text-text-secondary text-[11px]">
                    Do not modify or re-encode suspect URLs, headers, or downloaded payloads. Export raw incident records immediately.
                  </p>
                </div>
                <div className="p-3 rounded-lg border border-border bg-card-elevated/40 space-y-1">
                  <span className="font-semibold text-text-primary block font-mono">2. Compute Cryptographic SHA-256 Hashes</span>
                  <p className="text-text-secondary text-[11px]">
                    Use the Evidence tool to calculate and log the NIST-standard SHA-256 hash immediately upon artifact acquisition.
                  </p>
                </div>
                <div className="p-3 rounded-lg border border-border bg-card-elevated/40 space-y-1">
                  <span className="font-semibold text-text-primary block font-mono">3. Document Timestamps & Network Route</span>
                  <p className="text-text-secondary text-[11px]">
                    Ensure local machine time is synchronized via NTP. Include IP addresses, TLS handshake certificates, and DNS records.
                  </p>
                </div>
                <div className="p-3 rounded-lg border border-border bg-card-elevated/40 space-y-1">
                  <span className="font-semibold text-text-primary block font-mono">4. Export Signed PDF Incident Report</span>
                  <p className="text-text-secondary text-[11px]">
                    Download the official CyberGuard AI incident report PDF from the Reports section to submit alongside the formal police complaint.
                  </p>
                </div>
              </div>
            </Card>
          </main>
        </div>
      </div>
    </ProtectedRoute>
  );
}
