"use client";

import React, { useState } from "react";
import Link from "next/link";
import { 
  AlertTriangle, 
  ShieldAlert, 
  FileCheck2, 
  PhoneCall, 
  ChevronDown,
  ChevronUp,
  Search
} from "lucide-react";
import { Sidebar } from "@/components/layout/sidebar";
import { Header } from "@/components/layout/header";
import { ProtectedRoute } from "@/components/auth/protected-route";

interface LegalSection {
  section: string;
  title: string;
  act: string;
  description: string;
  penalties: string;
  relevance: string;
}

const STATUTORY_SECTIONS: LegalSection[] = [
  {
    section: "Section 66D",
    title: "Cheating by Personation Using Computer Resource",
    act: "Information Technology Act, 2000",
    description: "Applies directly to phishing schemes, fraudulent banking portals, spoofed sender domains, and fake job/lottery scams where an offender impersonates a legitimate entity to deceive victims.",
    penalties: "Imprisonment up to 3 years and fine up to ₹1,00,000.",
    relevance: "Primary statutory provision for reporting malicious URLs and phishing scams detected by CyberGuard AI."
  },
  {
    section: "Section 66C",
    title: "Identity Theft & Credential Theft",
    act: "Information Technology Act, 2000",
    description: "Fraudulently or dishonestly making use of the electronic signature, password, or any other unique identification feature of any other person.",
    penalties: "Imprisonment up to 3 years and fine up to ₹1,00,000.",
    relevance: "Applicable when malicious websites harvest user login credentials, OTPs, or session tokens."
  },
  {
    section: "Section 43 & 43A",
    title: "Damage to Computer Systems & Failure to Protect Data",
    act: "Information Technology Act, 2000",
    description: "Penalty and compensation for unauthorized access, downloading data, introducing viruses, denial of service, and failure of corporate bodies to protect sensitive personal data.",
    penalties: "Civil liability; compensation to the victim for damages caused.",
    relevance: "Governs corporate data breach responsibilities and unauthorized malware deployments."
  },
  {
    section: "Section 66",
    title: "Computer-Related Offenses & Hacking",
    act: "Information Technology Act, 2000",
    description: "Dishonestly or fraudulently committing any act referred to in Section 43 that alters, damages, destroys or diminishes value or utility of computer information.",
    penalties: "Imprisonment up to 3 years or fine up to ₹5,00,000, or both.",
    relevance: "Covers unauthorized server intrusion, defacement, and deliberate exploitation of computer resources."
  },
  {
    section: "Section 65B",
    title: "Admissibility of Electronic Records",
    act: "Indian Evidence Act, 1872 / Bharatiya Sakshya Adhiniyam, 2023",
    description: "Requires a certificate validating that electronic records (screenshots, server logs, forensic hashes) were generated by a computer during regular operational usage without unauthorized alteration.",
    penalties: "Inadmissibility of digital evidence in court if procedural requirements are violated.",
    relevance: "Crucial for producing CyberGuard AI forensic reports and SHA-256 evidence hashes in official court proceedings."
  },
  {
    section: "DPDP Act 2023",
    title: "Digital Personal Data Protection Act",
    act: "Statute of the Republic of India (Act No. 22 of 2023)",
    description: "Establishes a statutory framework for processing digital personal data, safeguarding individuals' privacy rights, and mandating prompt breach reporting to the Data Protection Board.",
    penalties: "Penalties up to ₹250 Crores for significant data breaches and failure to observe security safeguards.",
    relevance: "Mandates security measures against credential stuffing and phishing data leaks."
  }
];

export default function CyberLawPage() {
  const [searchQuery, setSearchQuery] = useState("");
  const [expandedSection, setExpandedSection] = useState<string | null>("Section 66D");

  const filteredSections = STATUTORY_SECTIONS.filter(item => {
    if (!searchQuery.trim()) return true;
    const q = searchQuery.toLowerCase();
    return (
      item.section.toLowerCase().includes(q) ||
      item.title.toLowerCase().includes(q) ||
      item.description.toLowerCase().includes(q) ||
      item.relevance.toLowerCase().includes(q)
    );
  });

  return (
    <ProtectedRoute>
      <div className="app-cg">
        <Sidebar />
        <div className="main-cg">
          <Header />
          <main className="content-cg">
            
            {/* Page Title */}
            <div className="page-title-cg">
              <div>
                <h1>Cyber Law Information</h1>
                <p>Reference information for reporting and responding to cyber incidents.</p>
              </div>
              <Link href="/reports" className="btn-cg primary">
                View Reports
              </Link>
            </div>

            {/* Official Indian Reporting Notice from cyberguard-ai-ui */}
            <div className="card-cg" style={{ marginBottom: 14 }}>
              <div className="card-body-cg">
                <h3 style={{ fontSize: 14, margin: "0 0 6px", color: "var(--text)" }}>
                  Indian Cyber Crime Reporting
                </h3>
                <p style={{ fontSize: 11, color: "var(--muted)", lineHeight: 1.7, margin: "0 0 12px" }}>
                  Use official government resources for current reporting procedures, legal provisions and emergency contacts. This page should be treated as general information and not as legal advice.
                </p>
                <div className="notice-cg">
                  <AlertTriangle size={13} style={{ verticalAlign: "middle", marginRight: 7 }} />
                  Verify current legal requirements and official reporting channels before taking action. In case of financial fraud, call <strong>1930</strong> immediately.
                </div>
              </div>
            </div>

            {/* Emergency Channels Grid */}
            <div className="grid-cg grid3-cg" style={{ marginBottom: 14 }}>
              <div className="card-cg">
                <div className="card-body-cg">
                  <div style={{ display: "flex", alignItems: "center", gap: 8, color: "var(--blue)", marginBottom: 8 }}>
                    <PhoneCall size={16} />
                    <span style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase" }}>National Cyber Helpline</span>
                  </div>
                  <div style={{ fontSize: 20, fontWeight: 800, color: "var(--text)", fontFamily: "monospace" }}>
                    1930
                  </div>
                  <p style={{ fontSize: 10, color: "var(--muted)", marginTop: 4, margin: 0 }}>
                    Toll-free emergency reporting for immediate financial fraud freeze.
                  </p>
                </div>
              </div>

              <div className="card-cg">
                <div className="card-body-cg">
                  <div style={{ display: "flex", alignItems: "center", gap: 8, color: "var(--blue)", marginBottom: 8 }}>
                    <ShieldAlert size={16} />
                    <span style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase" }}>National Portal</span>
                  </div>
                  <div style={{ fontSize: 18, fontWeight: 800, color: "var(--text)", fontFamily: "monospace" }}>
                    cybercrime.gov.in
                  </div>
                  <p style={{ fontSize: 10, color: "var(--muted)", marginTop: 4, margin: 0 }}>
                    Official portal for lodging cyber crime complaints online.
                  </p>
                </div>
              </div>

              <div className="card-cg">
                <div className="card-body-cg">
                  <div style={{ display: "flex", alignItems: "center", gap: 8, color: "var(--blue)", marginBottom: 8 }}>
                    <FileCheck2 size={16} />
                    <span style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase" }}>CERT-In Desk</span>
                  </div>
                  <div style={{ fontSize: 16, fontWeight: 800, color: "var(--text)", fontFamily: "monospace" }}>
                    incident@cert-in.org.in
                  </div>
                  <p style={{ fontSize: 10, color: "var(--muted)", marginTop: 4, margin: 0 }}>
                    Incident response and security notifications.
                  </p>
                </div>
              </div>
            </div>

            {/* Applicable Statutory Provisions */}
            <div className="card-cg">
              <div className="card-head-cg">
                <div>
                  <h3>Statutory Provisions</h3>
                  <p>Information Technology Act & Bharatiya Sakshya Adhiniyam</p>
                </div>

                <div className="search-cg" style={{ width: 220, height: 32 }}>
                  <Search size={14} />
                  <input
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    placeholder="Search sections..."
                  />
                </div>
              </div>

              <div className="card-body-cg" style={{ padding: 0 }}>
                {filteredSections.map((item) => {
                  const isExpanded = expandedSection === item.section;

                  return (
                    <div key={item.section} style={{ borderBottom: "1px solid var(--line)" }}>
                      <div
                        onClick={() => setExpandedSection(isExpanded ? null : item.section)}
                        className="finding-cg"
                        style={{ padding: "13px 17px", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "space-between" }}
                      >
                        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
                          <span className="badge-cg blue" style={{ fontFamily: "monospace" }}>
                            {item.section}
                          </span>
                          <div>
                            <strong style={{ fontSize: 12, display: "block", color: "var(--text)" }}>
                              {item.title}
                            </strong>
                            <span style={{ fontSize: 10, color: "var(--muted)" }}>
                              {item.act}
                            </span>
                          </div>
                        </div>

                        <div style={{ color: "var(--muted)" }}>
                          {isExpanded ? <ChevronUp size={15} /> : <ChevronDown size={15} />}
                        </div>
                      </div>

                      {isExpanded && (
                        <div style={{ padding: "14px 17px", background: "var(--panel-2)", borderTop: "1px solid var(--line)" }}>
                          <p style={{ fontSize: 11, color: "var(--text)", lineHeight: 1.6, margin: "0 0 10px" }}>
                            {item.description}
                          </p>
                          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, fontSize: 10 }}>
                            <div style={{ padding: "8px 12px", background: "var(--panel)", borderRadius: 7, border: "1px solid var(--line)" }}>
                              <strong style={{ color: "var(--amber)", display: "block", marginBottom: 3 }}>Penalties</strong>
                              <span style={{ color: "var(--text)" }}>{item.penalties}</span>
                            </div>
                            <div style={{ padding: "8px 12px", background: "var(--panel)", borderRadius: 7, border: "1px solid var(--line)" }}>
                              <strong style={{ color: "var(--blue)", display: "block", marginBottom: 3 }}>Platform Context</strong>
                              <span style={{ color: "var(--text)" }}>{item.relevance}</span>
                            </div>
                          </div>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>

          </main>
        </div>
      </div>
    </ProtectedRoute>
  );
}
